title: Daozhi Tang's Homepage
page-top-title: Daozhi Tang
top-section-bg-text: Welcome to my homepage!
home-subtitle: Daozhi Tang&ensp;|&ensp;唐道智
copyright-text: '&copy; Daozhi Tang 2024-2025. All Rights Reserved.'
