<<<<<<< HEAD
title: Daozhi Tang's Homepage
page-top-title: Daozhi Tang
top-section-bg-text: Welcome to my homepage!
home-subtitle: Daozhi Tang&ensp;|&ensp;唐道智
copyright-text: '&copy; Daozhi Tang 2024-2025. All Rights Reserved.'
=======
title: Sen Li's Homepage
page-top-title: Sen Li
top-section-bg-text: Computer Science
home-subtitle: Sen Li&ensp;|&ensp;李森
copyright-text: '&copy; Sen Li 2023-2025. All Rights Reserved.'
>>>>>>> 5574a033ba7a136aa4b74208d49cade537fe0ad3
